### PR TITLE
Added 'Flight Testing and Design Challenges' post

### PR DESCRIPTION
**Pull request by unboundfire**
Post
--
* Flight Testing and Autonomous Design Challenges

### CODE REVIEW

**Comment by edj-boston** [comment]
@unboundfire Looks like some of the IMG_... images could get compressed with Kraken

**Comment by unboundfire** [comment]
@edj-boston I ran them through [gulp-kraken](https://github.com/kraken-io/gulp-kraken) with the default options already.  I'll try to run them again and I can set lossy to false maybe that is why they don't seem compressed.

**Comment by edj-boston** [comment]
Yeah, we should do lossy for JPG's. I used the WebUI and saw 50% savings.

Don't use lossy for vector-ish stuff though, obvsly.


Eric Johnson | VP of Engineering, Cloud
*Airware* | 343 Sansome St, Suite 1050, SF, CA 94104
Office: (877) 714-4828 | Fax: (877) 567-7828

**Comment by unboundfire** [comment]
@edj-boston Updated the image files

**Comment by edj-boston** [comment]
:+1:

**Pull request merged**
